services:
  fiotec-front-v3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_VERSAO_PLATAFORMA: "beta-3.0.x"
    container_name: fiotec-front-v3
    environment:
      NEXT_PUBLIC_VERSAO_PLATAFORMA: "beta-3.0.x"
    ports:
      - "4000:4000"
    restart: unless-stopped
