import type { Metadata } from "next";
import "./globals.css";
import { Sidebar } from "lucide-react";
import { SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupContent, SidebarGroupLabel, SidebarHeader, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const items = [
    {
      title: "Dashboard",
      url: "/",
      icon: Sidebar,
    },
    {
      title: "Configurações",
      url: "/settings",
      icon: Sidebar,
    },
  ]
  return (
    <html lang="pt-BR">
      <body
        className={`antialiased`}
      >
        <SidebarProvider>
          <Sidebar>
            <SidebarContent>
              
            </SidebarContent>
          </Sidebar>
        </SidebarProvider>
        {children}
        
      </body>
    </html>
  );
}
