import type { Metadata } from "next";
import "./globals.css";

import Image from "next/image";

import { Calendar, Home, Inbox, Search, Settings } from "lucide-react"
import { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupLabel, SidebarHeader, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  const items = [
    {
      title: "Home",
      url: "#",
      icon: Home,
    },
    {
      title: "Inbox",
      url: "#",
      icon: Inbox,
    },
    {
      title: "Calendar",
      url: "#",
      icon: Calendar,
    },
    {
      title: "Search",
      url: "#",
      icon: Search,
    },
    {
      title: "Settings",
      url: "#",
      icon: Settings,
    },
  ]

  return (
    <html lang="pt-BR">
      <body
        className={`antialiased bg-[#F5F5F5]`}
      >
        <div className="flex flex-col h-screen overflow-hidden">
          <header className="w-full bg-[#F5F5F5] px-4 py-6">
            Cabeçalho
          </header>
          <div className="flex flex-1">
            <SidebarProvider>
              <Sidebar
                variant="inset" collapsible="icon" className="relative"
              >
                <SidebarHeader className="flex flex-col gap-4">
                    <Image className="rounded-md" src="https://picsum.photos/100" alt="Logo" width={32} height={32} />
                  </SidebarHeader>
                  <SidebarContent>
                    <SidebarGroup>
                      <SidebarGroupLabel className="bg-zinc-200 rounded-md">
                        <h3 className="font-semibold">MInha Conta</h3>
                      </SidebarGroupLabel>
                      <SidebarMenu>
                        {items.map((item) => (
                          <SidebarMenuItem key={item.title}>
                            <SidebarMenuButton asChild>
                              <a href={item.url} className="flex items-center gap-2">
                                <item.icon size={20} />
                                <span>{item.title}</span>
                              </a>
                            </SidebarMenuButton>
                          </SidebarMenuItem>
                        ))}
                      </SidebarMenu>
                    </SidebarGroup>
                    <SidebarGroup>
                      <SidebarGroupLabel>
                        <h3>Configurações</h3>
                      </SidebarGroupLabel>
                    </SidebarGroup>
                  </SidebarContent>
                  <SidebarFooter>
                    <div className="flex items-center gap-4">
                      <Image className="rounded-md" src="https://picsum.photos/100" alt="Logo" width={32} height={32} />
                      <h1 className="text-lg font-semibold">
                      </h1>
                    </div>
                  </SidebarFooter>
            
              </Sidebar>
              <div
                style={{
                  borderTopLeftRadius: "20px",
                  backgroundColor: "white"
                }}
              >
                <SidebarTrigger className="mt-5 ml-5" />
              </div>
            </SidebarProvider>

            <div className="bg-white flex-1 pt-8 pl-7 pr-7">
              {children}
            </div>
          </div>
        </div>
        
      </body>
    </html>
  );
}
