#!/bin/sh

echo "🔍 Executando Semgrep antes do push..."

# Verifica o projeto com Semgrep usando as regras automáticas
# semgrep --config=auto .

# Caso queira falhar o push se encontrar problemas críticos:
semgrep --config=auto --error

echo "✓ Semgrep finalizado — push liberado."