#!/bin/sh

echo "🔍 Executando Semgrep antes do push..."

# Verifica o projeto com Semgrep usando as regras automáticas
# semgrep --config=auto .

# Caso queira falhar o push se encontrar problemas críticos:
npx semgrep --config=p/ci --include 'src/**/*.ts*'

echo "✓ Semgrep finalizado — push liberado."