name: Deploy no Servidor

on:
  push:
    branches:
      - master   # dispara só quando fizer push na branch master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar chave SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.IA_EDITAIS_SSH }}

      - name: Deploy no servidor
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.IP_HOST_IAEDITAIS }} << 'EOF'
            mkdir -p /home/ubuntu/iaeditais
            cd /home/ubuntu/iaeditais
            git pull origin main
            npm install --production
            npm run build
            pm2 restart app
          EOF