name: Deploy no Servidor

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar chave SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.IA_EDITAIS_SSH }}

      - name: Deploy no servidor via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.IP_HOST_IAEDITAIS }} << 'EOF'
            set -e

            echo "🚀 Iniciando deploy via docker-compose..."

            cd /home/ubuntu

            # Se a pasta não existir, cria
            if [ ! -d "iaEditais-prod" ]; then
              echo "📦 Repositório não encontrado. Clonando..."
              git clone -b main https://github.com/rafaelontour/ia_editais_fiocruz.git iaEditais-prod
              cd iaEditais-prod
            else
              echo "🔄 Repositório existente. Atualizando..."
              cd iaEditais-prod
              git fetch origin main
              git reset --hard origin/main
            fi

            # Garante que o docker compose funcione mesmo sem sudo
            export DOCKER_BUILDKIT=1

            # Limpa containers antigos
            docker compose down --rmi all --remove-orphans || true

            # Build e start usando docker-compose
            docker compose up -d --build

            echo "✅ Deploy concluído com docker compose!"
          EOF
